name: 'Merge branch'
description: 'A GitHub Action that manage git merge for any gitflow'
author: Miguel Savignano
inputs:
  type:
    type: 'labeled | now'
    required: false
    default: 'labeled'
  label_name:
    description: 'PR Label name'
    required: false
  target_branch:
    description: 'The name of target branch to merge'
    required: true
  from_branch:
    description: 'Alias head_to_merge input'
    required: false
  head_to_merge:
    description: 'The branch name or hash to merge. default GITHUB_SHA'
    required: false
  github_token:
    description: 'Github token'
    required: true
  message:
    description: 'Commit message'
    required: false
  disable_fastforwards:
    description: 'Does not merge the branch if no files have been changed'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-merge'
  color: 'purple'
